travis:
  secure:
    BINSTAR_TOKEN: oo4L/wjSnKFdeXVsbfAUKfRDKTWP1RThZUg7DjXr79n7sZfmV/8SSi/fL/ubVi+YzgDVKqcEkYsdz0saRLkC5ngGsEg5oFjchk7uFeF6Hu8N+xXXOz92ZIrySY70O/qCBbBrqHKG4uIHde+wE6iEnGRxA5QDrvOjYDbnD+kocw5FKQA1VaH7y4ZffQlgiyIM4xaCNBp6HGnTFs3MFWWFpaxxaeLcpHchSaC2zGdPqKLDsDLVuiEm0YQSEkXBr+yJ9PEKC2ItYSE8ZV3R/tDrhHIqmOQocV9iBYcfpJVahLe84HXDruNcT+NNtL9YvLr1EcROcT9/Y2ntVZdakO4tmcNeFErpT1ZuRevRHJ6KHu6iokPnNUx9BXrVAiVUd8nm2UO/2NMjgzlq+lyOiEqBJzicjDQx+1ENiF9ijw0o0ZmdgSpkRFqCB1Oo3AtrpqWqSAHGqG4dzfXeazjwSCGCj7NdzSIRMI3j84SRPNhdEp+CGAsAkCvft/IJ2Lk9GLNpoqzWGQUHv3QSArCr5RnE+c76kccLC89O4ZpRq9FuGUkpdQm1Nddy6Jgv6xpMqWLILEXaIoqbb6B746jQV/nPbh37UTVqKcpXNWJGhUQJur7yKSI7QgJH9a/oNeSSpNkrDpslf/WS7bRF4/0+ZEMVn4Rk5QTbP3PHncZEv0w2AnM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
