travis:
  secure:
    BINSTAR_TOKEN: onFEUcsgRHPMaJ1ksFEDUWkf7uT9+fiwy7kzkn5cp4lHmh8nHc3jRX2o1xUXqekfkJZeQ8bFtmk6U2jtbia2uJ5Eb+8faqkuFM9kTMSKy9Ch6wFh0lTAj9FJ6rwFNjEoVf5/CXnGjaVM1p1VBUR943gGCWFarboiXPjsLLo+YyUoHQk5UeynAWj/Rmt/6V6tmlJi4SVBEAaR485uRYAE5tfTMB9PQw2IhL0C9iQs552INW5y5nlTAX5djS/L5nEh7QVhrPgPvKhWBUoE5unaFy4O032MgJ1sTRU4P4tenmM/DKbW178rhUKPf6qbYS8xJcqu1R4u8usM/MKKZPflnb1apxEWnWVGx1jyvV3Lx/gnG+jFFH4/YMkcVk3kktArMxLncl9V0j4m75qIqMONO6SEyWLgOCqMwKLMtBjKdFnq/v5+nLCn6r3scNDR7WckW4ATG3Vj5IAVqpCZsj8rh3rd8Ywe7qIgWiTJ+gTRjSHfVkvtEnOJkXnwoe/DKnBG7VuVLfMjI1/C4hYQkwp8lcRFJxx9oO7/LRrXxgv7TR0x404Jo18leeU5Xnb/7cPHdVgvnTwBoloqHDBdv0AYYvL6vOCC4mwPvJ1yGl/R6ETURiMxEYsOFoNU9f+qeqOGDC7X1IhP9ytRja6rEFiGbKo81DEVwMxdW3LN8nrdw7Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
