travis:
  secure:
    BINSTAR_TOKEN: XMkHMEE+azffqxo5KAp0P47tcn4DFsOgFRZJrebrslBLz4ab4GopZg8f5T2y/EkEwS7ep/Fjcw8Z02v84LsizMiazdAUjOKBIzXi7rJ0YESxYCaNSwZcVW/dBOsslpyCppEUK2BlL3JPBQBeLbjUY68OcCW2xS0WJnAdrspm45xlk7ny/4ol0MKuHHf8NwOmdSvp4bPrhrpYqnJ32JxBLHW/LoyRw7u1BQvhYOVUZyJ03xUWFlenxUW8/lCBJ87NgE/c3GHHKg+VPlQowbod4wXmbexLY+L6l42xti9ckBhl47nxobQP25Pqd5t9O4EycL19Bt2LJ/nNOxpF3KwuumOg7nkyOm1Y7iG52gTtpbUkx2/KxYRP7Gq9PWOArqS1RnLZ/nX36wipujQ3w9+ZoY9fQrnusGemAXoJxyZU7MkcMteVGsuItjvQKhjSx0zX4rxLZ7b3Zt4D8i7q7qowaNEhCwCDEX9Si6bBgPX3uYYJFoLxpmG4bM4Ga5QXOSXjX6ZGWr7fhphwYuWx0LC7+jev07FoD/JRTTwfRi3KMNJkzPGQQQkjmnDQisJhRUHl90iIdDokiwsHH1D27CHTZGBTWti4zuunay/KfUcrEG7oE4Zf3BGYOGJFeHDWJOuxTyJcMFDsYh/w7hCkr22h8Xu9KbhKQlDbSLw70fBdft4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
